blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/0xharryriddle/kaizen/discussions
    about: Ask questions, share ideas, and discuss plans here.
